- name: DEMO is on Filters
  hosts: localhost
  vars:
    NAME: Rahul Jaya Kanth
  tasks:
  - name: convert into upper case 
    debug:
      msg: "Hello {{NAME | upper}}"

  - name: convert into lower case 
    debug:
      msg: "Hello {{NAME | lower}}"

  